In [ ]:
%matplotlib inline


Labelling connected components of an image
===========================================

This example shows how to label connected components of a binary image, using
the dedicated skimage.measure.label function.



In [7]:
# from skimage import measure
from skimage import filters
from skimage.measure import label, regionprops, regionprops_table
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

n = 12
l = 256
np.random.seed(1)
im = np.zeros((l, l))
points = l * np.random.random((2, n ** 2))
im[(points[0]).astype(np.int), (points[1]).astype(np.int)] = 1
im = filters.gaussian(im, sigma= l / (4. * n))
blobs = im > 0.7 * im.mean()

all_labels = measure.label(blobs)
print("labels {}".format(all_labels))
blobs_labels = measure.label(blobs, background=0)
properties =['area','perimeter','bbox','convex_area','bbox_area',
             'major_axis_length', 'minor_axis_length',
             'eccentricity']
df = pd.DataFrame(regionprops_table(blobs_labels, properties = properties))

df.head()


labels [[ 1  1  1 ...  6  6  6]
 [ 1  1  1 ...  6  6  6]
 [ 1  1  1 ...  6  6  6]
 ...
 [27 27 27 ... 25 25 25]
 [27 27 27 ... 25 25 25]
 [ 0  0 27 ... 25 25 25]]


AttributeError: '<class 'skimage.measure._regionprops.RegionProperties'>' object has no attribute 'compactness'